apiVersion: v1
kind: Secret
metadata:
  name: recrutai-secrets
  namespace: recrutai
type: Opaque
stringData:
  POSTGRES_PASSWORD: "96324486roua"
  REDIS_PASSWORD: "96324486roua"
  DJANGO_SECRET_KEY: "django-insecure-09z%gj7x!#qp0jyqbg&_xn7v8!^jef%fm0-#fi50*w-8iqahzz"
  DJANGO_SUPERUSER_PASSWORD: "96324486roua"
  EMAIL_HOST_PASSWORD: "votre_mot_de_passe"